# Generated by Django 3.2.7 on 2021-09-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aparatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('especificaciones', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.BigIntegerField()),
                ('aparatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparatos.aparatos')),
            ],
        ),
    ]
