# Generated by Django 3.2.7 on 2021-09-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('domicilio', models.CharField(max_length=200)),
                ('componentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.componentes')),
            ],
        ),
    ]
