# Generated by Django 3.2.9 on 2021-11-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricantes',
            name='componentes',
            field=models.CharField(max_length=200),
        ),
    ]
